In [307]:
import pandas as pd

In [308]:
def find_customers(customer: pd.DataFrame, product: pd.DataFrame) -> pd.DataFrame:
    all_products = set(product['product_key'])
    result = []

    for cid in customer['customer_id'].unique():
        products = set(customer.loc[customer['customer_id'] == cid, 'product_key'])
        if products == all_products:
            result.append(cid)

    return pd.DataFrame(result, columns=['customer_id'])

In [309]:
data = [[1, 5], [2, 6], [3, 5], [3, 6], [1, 6]]
customer = pd.DataFrame(data, columns=['customer_id', 'product_key']).astype({'customer_id':'Int64', 'product_key':'Int64'})
data = [[5], [6]]
product = pd.DataFrame(data, columns=['product_key']).astype({'product_key':'Int64'})

In [310]:
find_customers(customer, product)

   customer_id
0            1
1            3

In [311]:
customer['customer_id'].values.unique()

<IntegerArray>
[1, 2, 3]
Length: 3, dtype: Int64

In [312]:
customer.sort_values(by='customer_id', ascending=True, inplace=True)
customer[customer['customer_id'] == 1]['product_key'].tolist()
customer.sort_values(by='customer_id', ascending=True, inplace=True)
customer[customer['customer_id'] == 1]['product_key'].tolist().sort()== [6, 5].sort()

True

In [313]:
customer[customer['customer_id'] == 1]['product_key'].tolist()

[5, 6]

In [314]:
customer

   customer_id  product_key
0            1            5
4            1            6
1            2            6
2            3            5
3            3            6

In [315]:
customer['customer_id'].iloc[2]

2

In [316]:
product

   product_key
0            5
1            6

In [317]:
[1,2,3]==[2,3,1]

False