In [88]:
import pandas as pd

def list_products(products: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:
    orders = orders[(orders['order_date'].dt.month == 2) & (orders['order_date'].dt.year == 2020)].groupby('product_id')['unit'].sum().to_frame()
    orders = orders[orders['unit']>=100]
    orders = orders.merge(products[['product_id', 'product_name']], on='product_id', how='left').drop(columns=['product_id'])
    return orders

In [89]:
data = [[1, 'Leetcode Solutions', 'Book'], [2, 'Jewels of Stringology', 'Book'], [3, 'HP', 'Laptop'], [4, 'Lenovo', 'Laptop'], [5, 'Leetcode Kit', 'T-shirt']]
products = pd.DataFrame(data, columns=['product_id', 'product_name', 'product_category']).astype({'product_id':'Int64', 'product_name':'object', 'product_category':'object'})
data = [[1, '2020-02-05', 60], [1, '2020-02-10', 70], [2, '2020-01-18', 30], [2, '2020-02-11', 80], [3, '2020-02-17', 2], [3, '2020-02-24', 3], [4, '2020-03-01', 20], [4, '2020-03-04', 30], [4, '2020-03-04', 60], [5, '2020-02-25', 50], [5, '2020-02-27', 50], [5, '2020-03-01', 50]]
orders = pd.DataFrame(data, columns=['product_id', 'order_date', 'unit']).astype({'product_id':'Int64', 'order_date':'datetime64[ns]', 'unit':'Int64'})

In [90]:
list_products(products, orders)

   unit        product_name
0   130  Leetcode Solutions
1   100        Leetcode Kit

In [91]:
products

   product_id           product_name product_category
0           1     Leetcode Solutions             Book
1           2  Jewels of Stringology             Book
2           3                     HP           Laptop
3           4                 Lenovo           Laptop
4           5           Leetcode Kit          T-shirt

In [92]:
orders

    product_id order_date  unit
0            1 2020-02-05    60
1            1 2020-02-10    70
2            2 2020-01-18    30
3            2 2020-02-11    80
4            3 2020-02-17     2
5            3 2020-02-24     3
6            4 2020-03-01    20
7            4 2020-03-04    30
8            4 2020-03-04    60
9            5 2020-02-25    50
10           5 2020-02-27    50
11           5 2020-03-01    50