In [177]:
from contextlib import redirect_stderr

import pandas as pd

In [178]:
def sales_personp(sales_person: pd.DataFrame, company: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:
    red = company[company['name'] == 'RED']['com_id']
    if red.empty:
        return sales_person['name'].to_frame()
    red_id = red.values[0]
    sales_persons_red = orders['sales_id'].where(orders['com_id'] == red_id).dropna()
    sales_person = sales_person[~sales_person['sales_id'].isin(sales_persons_red)]['name'].to_frame()
    return sales_person

In [179]:
data = [[1, 'John', 100000, 6, '4/1/2006'], [2, 'Amy', 12000, 5, '5/1/2010'], [3, 'Mark', 65000, 12, '12/25/2008'], [4, 'Pam', 25000, 25, '1/1/2005'], [5, 'Alex', 5000, 10, '2/3/2007']]
sales_person = pd.DataFrame(data, columns=['sales_id', 'name', 'salary', 'commission_rate', 'hire_date']).astype({'sales_id':'Int64', 'name':'object', 'salary':'Int64', 'commission_rate':'Int64', 'hire_date':'datetime64[ns]'})
data = [[1, 'RED', 'Boston'], [2, 'ORANGE', 'New York'], [3, 'YELLOW', 'Boston'], [4, 'GREEN', 'Austin']]
company = pd.DataFrame(data, columns=['com_id', 'name', 'city']).astype({'com_id':'Int64', 'name':'object', 'city':'object'})
data = [[1, '1/1/2014', 3, 4, 10000], [2, '2/1/2014', 4, 5, 5000], [3, '3/1/2014', 1, 1, 50000], [4, '4/1/2014', 1, 4, 25000]]
orders = pd.DataFrame(data, columns=['order_id', 'order_date', 'com_id', 'sales_id', 'amount']).astype({'order_id':'Int64', 'order_date':'datetime64[ns]', 'com_id':'Int64', 'sales_id':'Int64', 'amount':'Int64'})

In [180]:
sales_personp(sales_person, company, orders)

   name
1   Amy
2  Mark
4  Alex

In [181]:
sales_person

   sales_id  name  salary  commission_rate  hire_date
0         1  John  100000                6 2006-04-01
1         2   Amy   12000                5 2010-05-01
2         3  Mark   65000               12 2008-12-25
3         4   Pam   25000               25 2005-01-01
4         5  Alex    5000               10 2007-02-03

In [182]:
company

   com_id    name      city
0       1     RED    Boston
1       2  ORANGE  New York
2       3  YELLOW    Boston
3       4   GREEN    Austin

In [183]:
orders

   order_id order_date  com_id  sales_id  amount
0         1 2014-01-01       3         4   10000
1         2 2014-02-01       4         5    5000
2         3 2014-03-01       1         1   50000
3         4 2014-04-01       1         4   25000

In [184]:
# orders = orders[~orders['com_id'].isin(company.loc[company['com_id'] == 1, 'com_id'])]
sales_persons_red = orders['sales_id'].where(orders['com_id'] == 1).dropna()
sales_persons_red

2    1
3    4
Name: sales_id, dtype: Int64

In [185]:
red = company[company['name'] == 'RED']['com_id']
if red.empty:
    print(company)
else: print('hui')

hui